---
name: Container

on:  # yamllint disable-line rule:truthy
  - push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/metadata-action@v5
        id: meta
        with:
          # TODO: switch to GCP artifact registry
          images: ghcr.io/${{ github.repository }}
          flavor: latest=auto
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha

      - uses: docker/build-push-action@v5
        with:
          context: .
          build-args: |
            JOBS=2
          target: production
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
